// <auto-generated />
namespace FitnessMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class prima : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prima));
        
        string IMigrationMetadata.Id
        {
            get { return "201607141526460_prima"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
